// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechTales.Persistence.Context;

#nullable disable

namespace TechTales.Persistence.Migrations
{
    [DbContext(typeof(DbtechtalesContext))]
    partial class DbtechtalesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TechTales.Domain.entities.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreationUser")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdHistoria")
                        .HasColumnType("int");

                    b.Property<int?>("IdReto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserDeleted")
                        .HasColumnType("int");

                    b.Property<int?>("UserMod")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdHistoria" }, "IdHistoria");

                    b.HasIndex(new[] { "IdReto" }, "IdReto");

                    b.HasIndex(new[] { "IdUsuario" }, "IdUsuario");

                    b.ToTable("comentarios", (string)null);
                });

            modelBuilder.Entity("TechTales.Domain.entities.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreationUser")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("UserDeleted")
                        .HasColumnType("int");

                    b.Property<int?>("UserMod")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUsuario" }, "IdUsuario")
                        .HasDatabaseName("IdUsuario1");

                    b.ToTable("historias", (string)null);
                });

            modelBuilder.Entity("TechTales.Domain.entities.Reto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreationUser")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdAdmin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("UserDeleted")
                        .HasColumnType("int");

                    b.Property<int?>("UserMod")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAdmin" }, "IdAdmin");

                    b.ToTable("retos", (string)null);
                });

            modelBuilder.Entity("TechTales.Domain.entities.RetosCompletados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreationUser")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCompletado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdReto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserDeleted")
                        .HasColumnType("int");

                    b.Property<int?>("UserMod")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdReto" }, "IdReto")
                        .HasDatabaseName("IdReto1");

                    b.HasIndex(new[] { "IdUsuario", "IdReto" }, "IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("IdUsuario2");

                    b.ToTable("retoscompletados", (string)null);
                });

            modelBuilder.Entity("TechTales.Domain.entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreationUser")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('usuario','admin')")
                        .HasDefaultValueSql("'usuario'");

                    b.Property<int?>("UserDeleted")
                        .HasColumnType("int");

                    b.Property<int?>("UserMod")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("TechTales.Domain.entities.VotosHistorias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreationUser")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Dislikes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaVoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdHistoria")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserDeleted")
                        .HasColumnType("int");

                    b.Property<int?>("UserMod")
                        .HasColumnType("int");

                    b.Property<bool>("Voto")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdHistoria" }, "IdHistoria")
                        .HasDatabaseName("IdHistoria1");

                    b.HasIndex(new[] { "IdUsuario", "IdHistoria" }, "IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("IdUsuario3");

                    b.ToTable("votoshistorias", (string)null);
                });

            modelBuilder.Entity("TechTales.Domain.entities.Comentario", b =>
                {
                    b.HasOne("TechTales.Domain.entities.Historia", "IdHistoriaNavigation")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdHistoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("comentarios_ibfk_2");

                    b.HasOne("TechTales.Domain.entities.Reto", "IdRetoNavigation")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdReto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("comentarios_ibfk_3");

                    b.HasOne("TechTales.Domain.entities.Usuario", "IdUsuarioNavigation")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("comentarios_ibfk_1");

                    b.Navigation("IdHistoriaNavigation");

                    b.Navigation("IdRetoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TechTales.Domain.entities.Historia", b =>
                {
                    b.HasOne("TechTales.Domain.entities.Usuario", "IdUsuarioNavigation")
                        .WithMany("Historia")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("historias_ibfk_1");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TechTales.Domain.entities.Reto", b =>
                {
                    b.HasOne("TechTales.Domain.entities.Usuario", "IdAdminNavigation")
                        .WithMany("Retos")
                        .HasForeignKey("IdAdmin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("retos_ibfk_1");

                    b.Navigation("IdAdminNavigation");
                });

            modelBuilder.Entity("TechTales.Domain.entities.RetosCompletados", b =>
                {
                    b.HasOne("TechTales.Domain.entities.Reto", "IdRetoNavigation")
                        .WithMany("Retoscompletados")
                        .HasForeignKey("IdReto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("retoscompletados_ibfk_2");

                    b.HasOne("TechTales.Domain.entities.Usuario", "IdUsuarioNavigation")
                        .WithMany("Retoscompletados")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("retoscompletados_ibfk_1");

                    b.Navigation("IdRetoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TechTales.Domain.entities.VotosHistorias", b =>
                {
                    b.HasOne("TechTales.Domain.entities.Historia", "IdHistoriaNavigation")
                        .WithMany("Votoshistoria")
                        .HasForeignKey("IdHistoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("votoshistorias_ibfk_2");

                    b.HasOne("TechTales.Domain.entities.Usuario", "IdUsuarioNavigation")
                        .WithMany("Votoshistoria")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("votoshistorias_ibfk_1");

                    b.Navigation("IdHistoriaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TechTales.Domain.entities.Historia", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Votoshistoria");
                });

            modelBuilder.Entity("TechTales.Domain.entities.Reto", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Retoscompletados");
                });

            modelBuilder.Entity("TechTales.Domain.entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Historia");

                    b.Navigation("Retos");

                    b.Navigation("Retoscompletados");

                    b.Navigation("Votoshistoria");
                });
#pragma warning restore 612, 618
        }
    }
}
